In [3]:
import numpy as np
import pandas as pd

In [16]:
class PCA:
  def __init__(self, n_components=100):
    self.n_components = n_components
    self.components = None
    self.mean = None
  
  def fit(self, X):

    # 1- Subtract the mean from every column (mean centering)
    self.mean = np.mean(X, axis=0)
    X = X - self.mean

    # 2- calculates convariance (needs samples as columns)
    covariance = np.cov(X.T)

    # 3- calculates eigenvalues and eigenvectors from convariance matrix
    eigenvalues, eigenvectors = np.linalg.eig(covariance)

    # 4- transpose for easier calculations
    eigenvectors = eigenvectors.T

    # 5- sort eigenvectors
    idxs = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[idxs]
    eigenvectors = eigenvectors[idxs]

    # 6- Pick top n eigenvectors as principal components
    self.components = eigenvectors[0: self.n_components]
  
  def transform(self, X):
    
    X = X - self.mean
    return np.dot(X, self.components.T)

In [24]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/mnist_012.csv')
df.head()

0  1  2  3  4  5  6  7  8  ...  776  777  778  779  780  781  782  783  784
0  2  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
1  1  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
2  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
3  1  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0
4  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0    0

[5 rows x 785 columns]

In [7]:
df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '775', '776', '777', '778', '779', '780', '781', '782', '783', '784'],
      dtype='object', length=785)

In [25]:
Y = df.loc[:,'0']
X = df.drop(['0'], axis=1)

In [13]:
df.shape

(3147, 785)

In [20]:
pca = PCA(2)

In [21]:
pca.fit(X)

In [23]:
pca.transform(X[:5])

array([[  134.2724107 +0.j,  -107.74010173+0.j],
       [  970.41512047+0.j,   371.81582238+0.j],
       [-1267.52970321+0.j,   263.23020735+0.j],
       [ 1066.12355285+0.j,   239.33164202+0.j],
       [-1037.17691551+0.j,   427.39418566+0.j]])

In [27]:
mean = np.mean(X, axis=0)

In [29]:
X = X - mean

In [30]:
X

1    2    3    4    5    6    7  ...  778  779  780  781  782  783  784
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
3142  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3143  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3144  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3145  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3146  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[3147 rows x 784 columns]

In [31]:
X.shape

(3147, 784)

In [32]:
X.T.shape

(784, 3147)

In [34]:
covariance = np.cov(X.T)
covariance.shape

(784, 784)

In [39]:
eigenvalues, eigenvectors = np.linalg.eig(covariance)
eigenvalues.shape

(784,)

In [40]:
eigenvectors.shape

(784, 784)

In [41]:
eigenvectors

array([[0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       ...,
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 1.+0.j]])

In [42]:
eigenvectors = eigenvectors.T

In [43]:
eigenvectors

array([[0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       ...,
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 1.+0.j]])

In [44]:
idxs = np.argsort(eigenvalues)

In [48]:
idxs[::-1]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  75,  74,  73,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 109, 108, 110, 111, 112, 113, 115, 116, 117,
       114, 118, 120, 119, 121, 122, 123, 124, 125, 126, 127, 129, 128,
       131, 130, 134, 132, 140, 133, 137, 136, 135, 139, 144, 142, 143,
       141, 138, 145, 146, 147, 148, 149, 150, 152, 151, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 166, 165, 167, 168,
       169, 170, 172, 171, 173, 174, 175, 176, 178, 180, 181, 17

In [52]:
idxs = idxs[::-1]

In [53]:
eigenvalues = eigenvalues[idxs]
eigenvectors = eigenvectors[idxs]

In [58]:
eigenvectors[0:4].shape

(4, 784)